name = "EstimatingEquationsRegression"
uuid = "29055884-00e7-4984-94b8-2baec6a723d6"
authors = ["Kerby Shedden <kshedden@umich.edu>"]
version = "0.1.1"

[deps]
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"

[compat]
Aqua = "0.8"
BlockDiagonals = "0.1"
DataFrames = "1.7"
Distributions = "0.25"
GLM = "1.9"
LinearAlgebra = "1.9"
Optim = "1.9"
PrettyTables = "3.0"
Printf = "1.9"
StatsAPI = "1.7"
StatsBase = "0.34"
StatsModels = "0.7"
Test = "1.9"
julia = "1.9"
RCall = "0.14"
ReTestItems = "1.35"
StableRNGs = "1.0"
FiniteDifferences = "0.12"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"

[targets]
test = ["Aqua", "Test", "ReTestItems", "StableRNGs", "RCall", "FiniteDifferences"]
